---
title: "Test Script for Shiny App"
author: "Michael Mullarkey"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
## setting working directory
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, include = FALSE)

```

```{r loading packages}

if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)
if(!require(skimr)){install.packages('skimr')}
library(skimr)
if(!require(glue)){install.packages('glue')}
library(glue)
if(!require(diffdf)){install.packages('diffdf')}
library(diffdf)
if(!require(janitor)){install.packages('janitor')}
library(janitor)

```

```{r reading in the data}

# Want a function that reads in list of dataframes

# find all file names ending in .csv 
files <- dir(pattern = "*.csv")

# Reading in all the files into a list of dataframes and doing initial selecting down of variables relevant to the dashboard

data_list <- files %>%
  map(read_csv) %>% 
  map(~dplyr::select(.x, contains("ethnicity"),contains("race"),contains("age"),contains("sex"),contains("gender"),contains("orientation"),contains("cond"),
                     contains("qual"),contains("like"),contains("dislike"),contains("pfs"),contains("pswq"),contains("cdi"),contains("idas"),contains("phq"),contains("mfq"),
                     contains("ss_choice_factor"),contains("sitb"),contains("identify_diff_gender_than_bio_sex_factor"))) %>% 
  map(~dplyr::select(.x, -contains("tim"))) %>% 
  print()

# Breaking out individual datasets to do data cleaning that's necessary for individual dataframes https://stackoverflow.com/questions/59169631/split-a-list-into-separate-data-frame-in-r

map(data_list, ~tibble(.x)) %>%
    set_names(str_c("df_", 1:4)) %>% 
    list2env(.GlobalEnv)

```

```{r clean empower}

# Cleaning Empower data

empower <- df_1 %>% 
  dplyr::rename(racial_identity = parent_ethnicity) %>% 
  rowwise() %>% 
  mutate(sgm = any(c_across(c(parent_gender_agender,parent_gender_intersex, parent_gender_other:parent_gender_notsure)))) %>% 
  ungroup() %>% 
  mutate(race_minoritized = factor(case_when(
    
    str_detect(racial_identity, "White") == TRUE ~ "No",
    str_detect(racial_identity, "White") == FALSE &  str_detect(parent_ethnicity_other_text, "white") ~ "No",
    TRUE ~ "Yes"
    
    )),
         randomized = factor(ifelse(is.na(condition), "No", "Yes")),
         qual_feed = factor(ifelse(is.na(pfs_liked), "No", "Yes")),
         sitb_assess = factor("No"),
         non_rand_treat = factor("No"),
         rec_ssi = factor(ifelse(randomized == "Yes" | non_rand_treat == "Yes", "Yes", "No")),
         age = 18, # We don't know the age but want these folks to be included in the dashboard for folks looking for adults
         parent_report = factor("Yes"),
         self_report = factor("Yes"),
         study = factor("Empower RCT")) %>% 
  dplyr::select(age, race_minoritized, sgm, sitb_assess, qual_feed, randomized, non_rand_treat, rec_ssi, self_report, parent_report, study) %>% 
  print()

```

```{r clean cope}

# Cleaning COPE data

cope <- df_2 %>% 
  #dplyr::rename(racial_identity = parent_ethnicity) %>% 
  rowwise() %>% 
  mutate(gen_minoritized = any(c_across(c(b_dem_gender_not_sure:b_dem_gender_male_to_female_transgender_mtf, b_dem_gender_transgender))),
         orien_minoritized = factor(case_when(
           
          str_detect(b_dem_orientation, "Heterosexual/Straight") == TRUE ~ "No",
          is.na(b_dem_orientation) ~ NA_character_,
          TRUE ~ "Yes"
           
         )),
         sgm = as.logical(case_when(
           
           gen_minoritized == TRUE | orien_minoritized == "Yes" ~ TRUE,
           gen_minoritized == FALSE & orien_minoritized == "No" ~ FALSE,
           TRUE ~ NA
           
         )),
         race_minoritized = any(c_across(c(b_dem_race_american_indian_or_alaska_native:b_dem_race_native_hawaiian_or_other_pacific_islander, b_dem_race_black_african_american,b_dem_race_other_specify)))) %>% 
  ungroup() %>% 
  mutate(randomized = factor(ifelse(is.na(condition), "No", "Yes")),
         qual_feed = factor(ifelse(is.na(pi_pfs_like), "No", "Yes")),
         sitb_assess = factor(ifelse(is.na(b_sitbi_2), "No", "Yes")),
         non_rand_treat = factor("No"),
         rec_ssi = factor(ifelse(randomized == "Yes" | non_rand_treat == "Yes", "Yes", "No")),
         age = b_screener_age, # We don't know the age but want these folks to be included in the dashboard for folks looking for adults
         parent_report = factor("No"),
         self_report = factor("Yes"),
         race_minoritized = factor(case_when(
           
           race_minoritized == FALSE ~ "No",
           race_minoritized == TRUE ~ "Yes",
           TRUE ~ NA_character_
           
         )),
         study = factor("COPE")) %>% 
  dplyr::select(age, race_minoritized, sgm, sitb_assess, qual_feed, randomized, non_rand_treat, rec_ssi, self_report, parent_report, study) %>% 
  print()


```

```{r clean cope}

# Cleaning COPE data

covid <- df_3 %>% 
  #dplyr::rename(racial_identity = parent_ethnicity) %>% 
  mutate(gen_minoritized = factor(case_when(
    
    str_detect(gender, "Man") == T ~ "No",
    str_detect(gender, "Woman") == T ~ "No",
    is.na(gender) ~ NA_character_,
    TRUE ~ "Yes"
    
  )),
         orien_minoritized = factor(case_when(
           
          str_detect(sexual_orientation, "Heterosexual") == TRUE ~ "No",
          is.na(sexual_orientation) ~ NA_character_,
          TRUE ~ "Yes"
           
         )),
         sgm = as.logical(case_when(
           
           gen_minoritized == "Yes" | orien_minoritized == "Yes" ~ TRUE,
           gen_minoritized == "No" & orien_minoritized == "No" ~ FALSE,
           TRUE ~ NA
           
         )),
         race_minoritized = factor(case_when(
    
    str_detect(race_eth, "White, Non-Hispanic") == T ~ "No",
    is.na(race_eth) ~ NA_character_,
    TRUE ~ "Yes"
    
  ))) %>% 
  mutate(randomized = factor(ifelse(is.na(cond), "No", "Yes")),
         qual_feed = factor("No"),
         sitb_assess = factor("No"),
         non_rand_treat = factor("No"),
         rec_ssi = factor(ifelse(randomized == "Yes" | non_rand_treat == "Yes", "Yes", "No")),
         parent_report = factor("No"),
         self_report = factor("Yes"),
         study = factor("COVID RR")) %>% 
  dplyr::select(age, race_minoritized, sgm, sitb_assess, qual_feed, randomized, non_rand_treat, rec_ssi, self_report, parent_report, study) %>% 
  print()


```


```{r clean yes original data collection}

# Cleaning COPE data

yes_orig <- df_4 %>% 
  #dplyr::rename(racial_identity = parent_ethnicity) %>% 
  mutate(gen_minoritized = factor(case_when(
    
    str_detect(identify_diff_gender_than_bio_sex_factor, "Yes") == T ~ "Yes",
    str_detect(identify_diff_gender_than_bio_sex_factor, "Unsure") == T ~ "Yes",
    is.na(identify_diff_gender_than_bio_sex_factor) ~ NA_character_,
    TRUE ~ "No"
    
  )),
         orien_minoritized = factor(case_when(
           
          str_detect(sexual_orientation, "Heterosexual") == TRUE ~ "No",
          str_detect(sexual_orientation, "I do not want to respond") == TRUE ~ "No",
          is.na(sexual_orientation) ~ NA_character_,
          TRUE ~ "Yes"
           
         )),
         sgm = as.logical(case_when(
           
           gen_minoritized == "Yes" | orien_minoritized == "Yes" ~ TRUE,
           gen_minoritized == "No" & orien_minoritized == "No" ~ FALSE,
           TRUE ~ NA
           
         )),
         race_minoritized = factor(case_when(
    
    str_detect(race_ethnicity, "Caucasian[:punct:]") == T ~ "Yes",
    str_detect(race_ethnicity, "Caucasian") == T ~ "No",
    is.na(race_ethnicity) ~ NA_character_,
    TRUE ~ "Yes"
    
  )),
  age = as.numeric(str_extract(age, "[:digit:][:digit:]"))) %>% 
  mutate(randomized = factor("No"),
         qual_feed = factor(ifelse(is.na(pi_like_activity_qual), "No", "Yes")),
         sitb_assess = factor("No"),
         non_rand_treat = factor("Yes"),
         rec_ssi = factor(ifelse(randomized == "Yes" | non_rand_treat == "Yes", "Yes", "No")),
         parent_report = factor("No"),
         self_report = factor("Yes"),
         study = factor("YES Original")) %>% 
  dplyr::select(age, race_minoritized, sgm, sitb_assess, qual_feed, randomized, non_rand_treat, rec_ssi, self_report, parent_report, study) %>% 
  print()

```

```{r comparing data frames}

# Comparing the data frames once

compare_df_cols_same(empower, cope)

# Do it for all possible comparisons (Right now this includes comparisons of the data frames against themselves)

dfs_1 <- tibble(data_1 = list(empower, cope, covid, yes_orig))
dfs_2 <- tibble(data_2 = list(empower, cope, covid, yes_orig))

df_combos <- expand_grid(dfs_1, dfs_2) %>% 
  print()

map2(df_combos$data_1, df_combos$data_2, ~{
  
  compare_df_cols_same(.x, .y)
  
})

# Since that's true, will bind all data together

all_dash <- empower %>% 
  bind_rows(cope) %>% 
  bind_rows(covid) %>% 
  bind_rows(yes_orig) %>% 
  mutate(id = row_number(),
         rand_id = sample(id),
         sgm = factor(case_when(
           sgm == TRUE ~ "Yes",
           sgm == FALSE ~ "No",
           TRUE ~ NA_character_
         )))

glimpse(all_dash)

write_rds(all_dash, "LSMH_Data_Dashboard/lsmh_dash_data.rds")

# Notes as of right now: All parents in BRAVE are given age of 18 since the age variable seems to be missing. For original YES data collection all participants were given the minimum age of the age range they selected (Ex. "11-13" would be 11)

```

```{r}

## Now testing the functions within the app

# Checking if length is already 2, and if not repeat the value to make it be 2, if yes then retain both values

# Check that this framework works in all cases

vec_var <- enframe(c("Yes","No")) %>% 
  mutate(row = row_number()) %>% 
  mutate(weight = case_when(
    max(row) == 1 & row == 1 ~ 2,
    max(row) == 2 & row == 1 ~ 1,
    max(row) == 2 & row == 2 ~ 1)) %>%
  uncount() %>% 
  dplyr::select(value) %>% 
  deframe() %>% 
  print()

vec_var <- enframe(c("Yes")) %>% 
  mutate(row = row_number()) %>% 
  mutate(weight = case_when(
    max(row) == 1 & row == 1 ~ 2,
    max(row) == 2 & row == 1 ~ 1,
    max(row) == 2 & row == 2 ~ 1)) %>%
  uncount() %>% 
  dplyr::select(value) %>% 
  deframe() %>% 
  print()

vec_var <- enframe(c("No")) %>% 
  mutate(row = row_number()) %>% 
  mutate(weight = case_when(
    max(row) == 1 & row == 1 ~ 2,
    max(row) == 2 & row == 1 ~ 1,
    max(row) == 2 & row == 2 ~ 1)) %>%
  uncount() %>% 
  dplyr::select(value) %>% 
  deframe() %>% 
  print()

# Write a function

make_screen <- function(screen_var){
  
  vec_var <- enframe(screen_var) %>% 
  mutate(row = row_number()) %>% 
  mutate(weight = case_when(
    max(row) == 1 & row == 1 ~ 2,
    max(row) == 2 & row == 1 ~ 1,
    max(row) == 2 & row == 2 ~ 1)) %>%
  uncount() %>% 
  dplyr::select(value) %>% 
  deframe()
  
}

# Apply it once 

test_ex <- make_screen(c(NA_character_))

# Apply it across multiple vectors

race_var <- "No"
sgm_var <- c("Yes", "No")
sitb_var <- "Yes"
# qual_var <- c(NA_character_)

screening <- list(race_var = race_var, sgm_var = sgm_var, sitb_var = sitb_var)

multi_ex <- map_dfc(screening, make_screen) %>% 
  print()

# Use that data to filter the dataset (Potential future problem, if this isn't assessed/there's an NA the person gets dropped from all inclusion criteria even if they would otherwise qualify, need to figure out if there's a fix for this. In the meantime just tell folks they have to leave at least one box checked in each category)

data_highlight <- all_dash %>% 
        filter(sgm == deframe(multi_ex[1,"sgm_var"]) | sgm == deframe(multi_ex[2,"sgm_var"]),
               race_minoritized == deframe(multi_ex[1,"race_var"]) | race_minoritized == deframe(multi_ex[2,"race_var"]),
               sitb_assess == deframe(multi_ex[1,"sitb_var"]) | sitb_assess == deframe(multi_ex[2,"sitb_var"])) %>% 
  print()


create_scatter <- function(.data, min_age, max_age, race_var, sgm_var, sitb_var, qual_var, rand_var, non_rand_var, rec_ssi_var, self_var, parent_var){
    
    screening <- list(race_pipe = {{race_var}}, sgm_pipe = {{sgm_var}}, sitb_pipe = {{sitb_var}}, qual_pipe = {{qual_var}}, rand_pipe = {{rand_var}},
                      non_rand_pipe = {{non_rand_var}}, rec_ssi_pipe = {{rec_ssi_var}}, self_pipe = {{self_var}}, parent_pipe = {{parent_var}})
    
    multi_ex <- map_dfc(screening, make_screen)
  
    data_highlight <- .data %>% 
        filter(age >= {{min_age}} & age <= {{max_age}},
               sgm == deframe(multi_ex[1,"sgm_pipe"]) | sgm == deframe(multi_ex[2,"sgm_pipe"]),
               race_minoritized == deframe(multi_ex[1,"race_pipe"]) | race_minoritized == deframe(multi_ex[2,"race_pipe"]),
               sitb_assess == deframe(multi_ex[1,"sitb_pipe"]) | sitb_assess == deframe(multi_ex[2,"sitb_pipe"]),
               qual_feed == deframe(multi_ex[1,"qual_pipe"]) | qual_feed == deframe(multi_ex[2,"qual_pipe"]),
               randomized == deframe(multi_ex[1,"rand_pipe"]) | randomized == deframe(multi_ex[2,"rand_pipe"]),
               non_rand_treat == deframe(multi_ex[1,"non_rand_pipe"]) | non_rand_treat == deframe(multi_ex[2,"non_rand_pipe"]),
               rec_ssi == deframe(multi_ex[1,"rec_ssi_pipe"]) | rec_ssi == deframe(multi_ex[2,"rec_ssi_pipe"]),
               self_report == deframe(multi_ex[1,"self_pipe"]) | self_report == deframe(multi_ex[2,"self_pipe"]),
               parent_report == deframe(multi_ex[1,"parent_pipe"]) | parent_report == deframe(multi_ex[2,"parent_pipe"]))
    
    .data %>% 
        ggplot(aes(x=id,y=rand_id)) + 
        geom_jitter(alpha=0.3) +
        geom_point(data=data_highlight, 
                   aes(x=id,y=rand_id), 
                   color='blue', alpha = 0.6) +
        labs(x = "Participant ID", y = "Random Number (For Plotting)")
    
}

all_dash %>% 
  create_scatter(min_age = 13, max_age= 50, race_var = c("Yes", "No"), sgm_var = c("Yes", "No"), sitb_var = "Yes", qual_var = c("Yes","No"),
                 rand_var = c("Yes","No"), non_rand_var = "No", rec_ssi_var = c("Yes"),self_var=c("Yes"),parent_var=c("Yes","No"))

```


